[package]
name = "foundationdb-sys"
version = "0.0.2"
authors = ["Benjamin Fry <benjaminfry@me.com>"]

description = """
Bindings to the C api for FoundationDB
"""

repository = "https://github.com/bluejekyll/foundationdb-rs"
license = "MIT/Apache-2.0"

[dependencies]


[build-dependencies]
bindgen = "0.36"
