[package]
name = "foundationdb"
version = "0.0.0"
authors = ["Benjamin Fry <benjaminfry@me.com>"]

description = """
Bindings to the C api for FoundationDB
"""

repository = "https://github.com/bluejekyll/foundation-rs"
license = "MIT/Apache-2.0"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
foundationdb-sys = { version = "0.0.1", path = "../foundationdb-sys" }